import type { INodeProperties } from 'n8n-workflow';

export const createDescription: INodeProperties[] = [
	{
		displayName: 'Handle As User Edit',
		name: 'handle_as_user_edit',
		type: 'boolean',
		default: false,
		description:
			'Whether to handle the line item as a user edit to an existing line item from automatic sources (e.g. Stripe, Chargebee, Recurly, etc.)',
		displayOptions: { show: { resource: ['line_item'], operation: ['create'] } },
		routing: { request: { qs: { handle_as_user_edit: '={{$value}}' } } },
	},
	{
		displayName: 'Invoice UUID',
		name: 'invoiceUUID',
		type: 'string',
		default: '',
		description: 'The UUID of the Invoice to which the Line Item belongs',
		displayOptions: { show: { resource: ['line_item'], operation: ['create'] } },
		required: true,
		routing: { request: { url: '=/import/invoices/{{$value}}/line_items' } },
	},
	{
		displayName: 'Type',
		name: 'type',
		type: 'options',
		default: 'subscription',
		description: 'The type of the line item',
		options: [
			{ name: 'Subscription', value: 'subscription' },
			{ name: 'One Time', value: 'one_time' },
		],
		displayOptions: { show: { resource: ['line_item'], operation: ['create'] } },
		routing: { request: { body: { type: '={{$value}}' } } },
	},
	{
		displayName: 'Amount in Cents',
		name: 'amount_in_cents',
		type: 'number',
		default: 0,
		displayOptions: { show: { resource: ['line_item'], operation: ['create'] } },
		routing: { request: { body: { amount_in_cents: '={{$value}}' } } },
	},
	{
		displayName: 'Subscription Line Item Fields',
		name: 'subscriptionLineItemFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['line_item'], operation: ['create'], type: ['subscription'] } },
		options: [
			{
				displayName: 'Subscription External ID',
				name: 'subscription_external_id',
				type: 'string',
				default: '',
				description: 'A reference identifier for the subscription in your system',
				routing: { request: { body: { subscription_external_id: '={{$value}}' } } },
			},
			{
				displayName: 'Subscription Set External ID',
				name: 'subscription_set_external_id',
				type: 'string',
				default: '',
				description:
					'A reference identifier for a set of subscriptions in order to group several subscriptions into one set',
				routing: { request: { body: { subscription_set_external_id: '={{$value}}' } } },
			},
			{
				displayName: 'Plan UUID',
				name: 'plan_uuid',
				type: 'string',
				default: '',
				description: 'The ChartMogul UUID of the plan associated with the subscription',
				routing: { request: { body: { plan_uuid: '={{$value}}' } } },
			},
			{
				displayName: 'Service Period Start',
				name: 'service_period_start',
				type: 'dateTime',
				default: '',
				description: 'The start date of the service period for the subscription line item',
				routing: { request: { body: { service_period_start: '={{ new Date($value).toISOString() }}' } } },
			},
			{
				displayName: 'Service Period End',
				name: 'service_period_end',
				type: 'dateTime',
				default: '',
				description: 'The end date of the service period for the subscription line item',
				routing: { request: { body: { service_period_end: '={{ new Date($value).toISOString() }}' } } },
			},
			{
				displayName: 'Prorated',
				name: 'prorated',
				type: 'boolean',
				default: false,
				description: 'Whether the subscription line item amount is prorated',
				routing: { request: { body: { prorated: '={{$value}}' } } },
			},
			{
				displayName: 'Proration Type',
				name: 'proration_type',
				type: 'options',
				default: 'differential',
				options: [
					{ name: 'Differential', value: 'differential' },
					{ name: 'Full', value: 'full' },
					{ name: 'Differential MRR', value: 'differential_mrr' },
				],
				routing: { request: { body: { proration_type: '={{$value}}' } } },
			},
		],
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		default: '',
		description: 'The description of the line item',
		displayOptions: { show: { resource: ['line_item'], operation: ['create'], type: ['one_time'] } },
		routing: { request: { body: { description: '={{$value}}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['line_item'], operation: ['create'] } },
		options: [
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				description: 'The unique identifier of the line item',
				routing: { request: { body: { external_id: '={{$value}}' } } },
			},
			{
				displayName: 'Quantity',
				name: 'quantity',
				type: 'number',
				default: 1,
				description: 'The quantity/seats of the product billed in the line item',
				routing: { request: { body: { quantity: '={{$value}}' } } },
			},
			{
				displayName: 'Discount Amount in Cents',
				name: 'discount_amount_in_cents',
				type: 'number',
				default: 0,
				routing: { request: { body: { discount_amount_in_cents: '={{$value}}' } } },
			},
			{
				displayName: 'Discount Code',
				name: 'discount_code',
				type: 'string',
				default: '',
				description: 'Optional reference code to identify the discount',
				routing: { request: { body: { discount_code: '={{$value}}' } } },
			},
			{
				displayName: 'Discount Description',
				name: 'discount_description',
				type: 'string',
				default: '',
				routing: { request: { body: { discount_description: '={{$value}}' } } },
			},
			{
				displayName: 'Tax Amount in Cents',
				name: 'tax_amount_in_cents',
				type: 'number',
				default: 0,
				routing: { request: { body: { tax_amount_in_cents: '={{$value}}' } } },
			},
			{
				displayName: 'Transaction Fee in Cents',
				name: 'transaction_fees_in_cents',
				type: 'number',
				default: 0,
				routing: { request: { body: { transaction_fees_in_cents: '={{$value}}' } } },
			},
			{
				displayName: 'Transaction Fee Currency',
				name: 'transaction_fees_currency',
				type: 'string',
				default: '',
				description: 'The three-letter currency code of the transaction fee',
				routing: { request: { body: { transaction_fees_currency: '={{$value}}' } } },
			},
			{
				displayName: 'Event Order',
				name: 'event_order',
				type: 'number',
				default: 0,
				description:
					'A numeric value that determines the sequence in which events are processed when multiple events occur at the same timestamp',
				routing: { request: { body: { event_order: '={{$value}}' } } },
			},
		],
	},
];
