import type { INodeProperties } from 'n8n-workflow';

export const createDescription: INodeProperties[] = [
	{
		displayName: 'Handle As User Edit',
		name: 'handle_as_user_edit',
		type: 'boolean',
		default: false,
		description:
			'Whether to handle as a user edit to an existing entry from automatic sources (e.g. Stripe, Chargebee, Recurly, etc.)',
		displayOptions: { show: { resource: ['event'], operation: ['create'] } },
		routing: { request: { qs: { handle_as_user_edit: '={{$value}}' } } },
	},
	{
		displayName: 'Data Source UUID',
		name: 'data_source_uuid',
		type: 'string',
		default: '',
		description: 'The UUID of the Data Source',
		displayOptions: { show: { resource: ['event'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { subscription_event: { data_source_uuid: '={{$value}}' } } } },
	},
	{
		displayName: 'Customer External ID',
		name: 'customer_external_id',
		type: 'string',
		default: '',
		description: 'The external ID of the customer associated with the subscription event',
		displayOptions: { show: { resource: ['event'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { subscription_event: { customer_external_id: '={{$value}}' } } } },
	},
	{
		displayName: 'Event Type',
		name: 'event_type',
		type: 'options',
		options: [
			{
				name: 'Subscription Cancellation (Retracted)',
				value: 'scheduled_subscription_cancellation_retracted',
			},
			{ name: 'Subscription Cancellation (Scheduled)', value: 'subscription_cancellation_scheduled' },
			{ name: 'Subscription Cancelled', value: 'subscription_cancelled' },
			{ name: 'Subscription Event Retracted', value: 'subscription_event_retracted' },
			{ name: 'Subscription Start', value: 'subscription_start' },
			{ name: 'Subscription Start (Retracted)', value: 'scheduled_subscription_start_retracted' },
			{ name: 'Subscription Start (Scheduled)', value: 'subscription_start_scheduled' },
			{ name: 'Subscription Update', value: 'subscription_updated' },
			{ name: 'Subscription Update (Retracted)', value: 'scheduled_subscription_update_retracted' },
			{ name: 'Subscription Update (Scheduled)', value: 'subscription_update_scheduled' },
		],
		default: 'subscription_cancelled',
		description: 'The type of subscription event',
		displayOptions: { show: { resource: ['event'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { subscription_event: { event_type: '={{$value}}' } } } },
	},
	{
		displayName: 'Event Date',
		name: 'event_date',
		type: 'dateTime',
		default: '',
		description: 'The date of the subscription event',
		displayOptions: { show: { resource: ['event'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { subscription_event: { event_date: '={{$value}}' } } } },
	},
	{
		displayName: 'Effective Date',
		name: 'effective_date',
		type: 'dateTime',
		default: '',
		description: 'The effective date of the subscription event',
		displayOptions: { show: { resource: ['event'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { subscription_event: { effective_date: '={{$value}}' } } } },
	},
	{
		displayName: 'Subscription External ID',
		name: 'subscription_external_id',
		type: 'string',
		default: '',
		description: 'The external ID of the subscription associated with the event',
		displayOptions: { show: { resource: ['event'], operation: ['create'] } },
		required: true,
		routing: {
			request: { body: { subscription_event: { subscription_external_id: '={{$value}}' } } },
		},
	},
	{
		displayName: 'Required Subscription Event Fields',
		name: 'requiredSubscriptionEventFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['event'],
				operation: ['create'],
				event_type: [
					'subscription_start',
					'subscription_start_scheduled',
					'subscription_updated',
					'subscription_update_scheduled',
				],
			},
		},
		options: [
			{
				displayName: 'Plan External ID',
				name: 'plan_external_id',
				type: 'string',
				default: '',
				description: 'The external ID of the plan associated with the subscription event',
				routing: { request: { body: { subscription_event: { plan_external_id: '={{$value}}' } } } },
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'string',
				default: '',
				placeholder: 'USD',
				routing: { request: { body: { subscription_event: { currency: '={{$value}}' } } } },
			},
			{
				displayName: 'Amount In Cents',
				name: 'amount_in_cents',
				type: 'number',
				default: 0,
				routing: { request: { body: { subscription_event: { amount_in_cents: '={{$value}}' } } } },
			},
			{
				displayName: 'Quantity',
				name: 'quantity',
				type: 'number',
				default: 1,
				routing: { request: { body: { subscription_event: { quantity: '={{$value}}' } } } },
			},
		],
	},
	{
		displayName: 'Retracted Event ID',
		name: 'retracted_event_id',
		type: 'string',
		default: '',
		description: 'The ID of the event being retracted',
		displayOptions: {
			show: {
				resource: ['event'],
				operation: ['create'],
				event_type: ['subscription_event_retracted'],
			},
		},
		required: true,
		routing: {
			request: { body: { subscription_event: { retracted_event_id: '={{$value}}' } } },
		},
	},
	{
		displayName: 'Additional Event Fields',
		name: 'additionalEventFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['event'], operation: ['create'] } },
		options: [
			{
				displayName: 'Subscription Set External ID',
				name: 'subscription_set_external_id',
				type: 'string',
				default: '',
				description: 'The external ID of the subscription set associated with the event',
				routing: {
					request: {
						body: { subscription_event: { subscription_set_external_id: '={{$value}}' } },
					},
				},
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				description: 'The external ID of the subscription event',
				routing: { request: { body: { subscription_event: { external_id: '={{$value}}' } } } },
			},
			{
				displayName: 'Event Order',
				name: 'event_order',
				type: 'number',
				default: 0,
				description:
					'A numeric value that determines the sequence in which events are processed when multiple events occur at the same timestamp',
				routing: { request: { body: { subscription_event: { event_order: '={{$value}}' } } } },
			},
			{
				displayName: 'Tax Amount In Cents',
				name: 'tax_amount_in_cents',
				type: 'number',
				default: 0,
				description: 'The tax amount in cents associated with the subscription event',
				routing: {
					request: { body: { subscription_event: { tax_amount_in_cents: '={{$value}}' } } },
				},
			},
		],
	},
];
