import type { INodeProperties } from 'n8n-workflow';

export const listDescription: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['event'], operation: ['list'] } },
		routing: {
			send: { paginate: '={{ $value }}' },
			output: {
				postReceive: [{ type: 'rootProperty', properties: { property: 'subscription_events' } }],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 200 },
		displayOptions: {
			show: { resource: ['event'], operation: ['list'] },
			hide: { returnAll: [true] },
		},
		routing: { request: { qs: { per_page: '={{$value}}' } } },
	},
	{
		displayName: 'Filter Options',
		name: 'filterOptions',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['event'], operation: ['list'] } },
		options: [
			{
				displayName: 'Customer External ID',
				name: 'customer_external_id',
				type: 'string',
				default: '',
				description: 'The external ID of the customer associated with the subscription event',
				routing: { request: { qs: { customer_external_id: '={{$value}}' } } },
			},
			{
				displayName: 'Data Source UUID',
				name: 'data_source_uuid',
				type: 'string',
				default: '',
				description: 'The UUID of the Data Source',
				routing: { request: { qs: { data_source_uuid: '={{$value}}' } } },
			},
			{
				displayName: 'Effective Date',
				name: 'effective_date',
				type: 'dateTime',
				default: '',
				description: 'The effective date of the subscription event',
				routing: { request: { qs: { effective_date: '={{$value}}' } } },
			},
			{
				displayName: 'Event Date',
				name: 'event_date',
				type: 'dateTime',
				default: '',
				description: 'The date of the subscription event',
				routing: { request: { qs: { event_date: '={{$value}}' } } },
			},
			{
				displayName: 'Event Type',
				name: 'event_type',
				type: 'options',
				options: [
					{
						name: 'Subscription Cancellation (Retracted)',
						value: 'scheduled_subscription_cancellation_retracted',
					},
					{ name: 'Subscription Cancellation (Scheduled)', value: 'subscription_cancellation_scheduled' },
					{ name: 'Subscription Cancelled', value: 'subscription_cancelled' },
					{ name: 'Subscription Event Retracted', value: 'subscription_event_retracted' },
					{ name: 'Subscription Start', value: 'subscription_start' },
					{ name: 'Subscription Start (Retracted)', value: 'scheduled_subscription_start_retracted' },
					{ name: 'Subscription Start (Scheduled)', value: 'subscription_start_scheduled' },
					{ name: 'Subscription Update', value: 'subscription_updated' },
					{ name: 'Subscription Update (Retracted)', value: 'scheduled_subscription_update_retracted' },
					{ name: 'Subscription Update (Scheduled)', value: 'subscription_update_scheduled' },
				],
				default: 'subscription_cancelled',
				description: 'The type of subscription event',
				routing: { request: { qs: { event_type: '={{$value}}' } } },
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				description: 'The external ID of the subscription event',
				routing: { request: { qs: { external_id: '={{$value}}' } } },
			},
			{
				displayName: 'Include Disabled Events',
				name: 'with_disabled',
				type: 'boolean',
				default: false,
				description: 'Whether to include disabled events in the response',
				routing: { request: { qs: { with_disabled: '={{$value}}' } } },
			},
			{
				displayName: 'Include Edit History',
				name: 'include_edit_histories',
				type: 'boolean',
				default: false,
				description: 'Whether to include edit histories in the response',
				routing: { request: { qs: { include_edit_histories: '={{$value}}' } } },
			},
			{
				displayName: 'Plan External ID',
				name: 'plan_external_id',
				type: 'string',
				default: '',
				description: 'The external ID of the plan associated with the subscription event',
				routing: { request: { qs: { plan_external_id: '={{$value}}' } } },
			},
			{
				displayName: 'Subscription External ID',
				name: 'subscription_external_id',
				type: 'string',
				default: '',
				description: 'The external ID of the subscription associated with the event',
				routing: { request: { qs: { subscription_external_id: '={{$value}}' } } },
			},
		],
	},
];
