import type { INodeProperties } from 'n8n-workflow';

export const createDescription: INodeProperties[] = [
	{
		displayName: 'Data Source UUID',
		name: 'data_source_uuid',
		type: 'string',
		default: '',
		description: 'The data source UUID where you want to store this contact record',
		displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { data_source_uuid: '={{$value}}' } } },
	},
	{
		displayName: 'Customer UUID',
		name: 'customerUUID',
		type: 'string',
		default: '',
		description: 'ChartMogul UUID of the Customer',
		displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { customer_uuid: '={{$value}}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
		options: [
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'name@email.com',
				description: "The contact's email address",
				routing: { request: { body: { email: '={{$value}}' } } },
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				description: 'A unique identifier for the contact in your own system',
				routing: { request: { body: { external_id: '={{$value}}' } } },
			},
			{
				displayName: 'First Name',
				name: 'first_name',
				type: 'string',
				default: '',
				description: "The contact's first name",
				routing: { request: { body: { first_name: '={{$value}}' } } },
			},
			{
				displayName: 'Last Name',
				name: 'last_name',
				type: 'string',
				default: '',
				description: "The contact's last name",
				routing: { request: { body: { last_name: '={{$value}}' } } },
			},
			{
				displayName: 'Last Seen',
				name: 'last_seen',
				type: 'dateTime',
				default: '',
				description: "A timestamp of when the contact was last active",
				routing: { request: { body: { last_seen: '={{$value}}' } } },
			},
			{
				displayName: 'LinkedIn',
				name: 'linked_in',
				type: 'string',
				default: '',
				description: "The contact's LinkedIn profile URL",
				routing: { request: { body: { linked_in: '={{$value}}' } } },
			},
			{
				displayName: 'Notes',
				name: 'notes',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				description: 'Any additional notes you wish to add about the contact',
				routing: { request: { body: { notes: '={{$value}}' } } },
			},
			{
				displayName: 'Phone',
				name: 'phone',
				type: 'string',
				default: '',
				description: "The contact's phone number",
				routing: { request: { body: { phone: '={{$value}}' } } },
			},
			{
				displayName: 'Position',
				name: 'position',
				type: 'number',
				typeOptions: { numberPrecision: 0 },
				default: 1,
				description: 'Sets the position of the contact in the UI',
				routing: { request: { body: { position: '={{$value}}' } } },
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: '',
				description: "The contact's job title",
				routing: { request: { body: { title: '={{$value}}' } } },
			},
			{
				displayName: 'Twitter',
				name: 'twitter',
				type: 'string',
				default: '',
				description: "The contact's Twitter URL",
				routing: { request: { body: { twitter: '={{$value}}' } } },
			},
			// Future fields to consider adding:
			// - custom attributes
		],
	},
];
