import type { INodeProperties } from 'n8n-workflow';

export const addContactDescription: INodeProperties[] = [
	{
		displayName: 'Customer UUID',
		name: 'customerUUID',
		type: 'string',
		default: '',
		description: 'ChartMogul UUID of the Customer',
		displayOptions: { show: { resource: ['customer'], operation: ['add_contact'] } },
		required: true,
	},
	{
		displayName: 'Data Source UUID',
		name: 'data_source_uuid',
		type: 'string',
		default: '',
		description: 'ChartMogul UUID of the Data Source',
		displayOptions: { show: { resource: ['customer'], operation: ['add_contact'] } },
		required: true,
		routing: { request: { body: { data_source_uuid: '={{$value}}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['customer'], operation: ['add_contact'] } },
		options: [
			{
				displayName: 'First Name',
				name: 'first_name',
				type: 'string',
				default: '',
				description: "The contact's first name",
				routing: { request: { body: { first_name: '={{$value}}' } } },
			},
			{
				displayName: 'Last Name',
				name: 'last_name',
				type: 'string',
				default: '',
				description: "The contact's last name",
				routing: { request: { body: { last_name: '={{$value}}' } } },
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'name@email.com',
				description: "The contact's email address",
				routing: { request: { body: { email: '={{$value}}' } } },
			},
			{
				displayName: 'Phone',
				name: 'phone',
				type: 'string',
				default: '',
				description: "The contact's phone number",
				routing: { request: { body: { phone: '={{$value}}' } } },
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: '',
				description: "The contact's job title",
				routing: { request: { body: { title: '={{$value}}' } } },
			},
			{
				displayName: 'LinkedIn',
				name: 'linked_in',
				type: 'string',
				default: '',
				description: "The contact's LinkedIn profile URL",
				routing: { request: { body: { linked_in: '={{$value}}' } } },
			},
			{
				displayName: 'Twitter',
				name: 'twitter',
				type: 'string',
				default: '',
				description: "The contact's Twitter URL",
				routing: { request: { body: { twitter: '={{$value}}' } } },
			},
			{
				displayName: 'Notes',
				name: 'notes',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				description: 'Any additional notes you wish to add about the contact',
				routing: { request: { body: { notes: '={{$value}}' } } },
			},
		],
	},
];
