import type { INodeProperties } from 'n8n-workflow';

export const createDescription: INodeProperties[] = [
	{
		displayName: 'Handle As User Edit',
		name: 'handle_as_user_edit',
		type: 'boolean',
		default: false,
		description:
			'Whether to handle the invoice as a user edit to an existing invoice from automatic sources (e.g. Stripe, Chargebee, Recurly, etc.)',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
		routing: { request: { qs: { handle_as_user_edit: '={{$value}}' } } },
	},
	{
		displayName: 'Customer UUID',
		name: 'customerUUID',
		type: 'string',
		description: 'ChartMogul UUID of the Customer',
		default: '',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
		required: true,
	},
	{
		displayName: 'Invoice External ID',
		name: 'externalId',
		type: 'string',
		default: '',
		description: 'The external ID of the invoice',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
		required: true,
	},
	{
		displayName: 'Date',
		name: 'date',
		type: 'dateTime',
		default: '',
		description: 'The date of the invoice',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
		required: true,
	},
	{
		displayName: 'Currency',
		name: 'currency',
		type: 'string',
		default: '',
		description: 'The currency of the invoice',
		placeholder: 'USD',
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
		required: true,
	},
	{
		displayName: 'Additional Invoice Fields',
		name: 'invoice',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
		options: [
			{
				displayName: 'Collection Method',
				name: 'collection_method',
				type: 'options',
				options: [
					{ name: 'Automatic', value: 'automatic' },
					{ name: 'Manual', value: 'manual' },
				],
				default: 'automatic',
				description: 'The collection method of the invoice',
			},
			{
				displayName: 'Customer External ID',
				name: 'customer_external_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Data Source UUID',
				name: 'dataSourceUUID',
				type: 'string',
				default: '',
				description: 'ChartMogul UUID of the Data Source',
			},
			{
				displayName: 'Due Date',
				name: 'due_date',
				type: 'dateTime',
				default: '',
				description: 'The due date of the invoice',
			},
		],
	},
	{
		displayName: 'Line Items',
		name: 'line_items',
		type: 'fixedCollection',
		placeholder: 'Add Line Item',
		typeOptions: { multipleValues: true },
		default: {},
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
		options: [
			{
				displayName: 'One Time',
				name: 'one_time',
				values: [
					{ displayName: 'Amount in Cents', name: 'amount_in_cents', type: 'number', default: 0 },
					{ displayName: 'Description', name: 'description', type: 'string', default: '' },
					{
						displayName: 'Discount Amount in Cents',
						name: 'discount_amount_in_cents',
						type: 'number',
						default: 0,
					},
					{ displayName: 'Discount Code', name: 'discount_code', type: 'string', default: '' },
					{
						displayName: 'Discount Description',
						name: 'discount_description',
						type: 'string',
						default: '',
					},
					{ displayName: 'Event Order', name: 'event_order', type: 'number', default: 0 },
					{ displayName: 'External ID', name: 'external_id', type: 'string', default: '' },
					{ displayName: 'Quantity', name: 'quantity', type: 'number', default: 1 },
					{
						displayName: 'Tax Amount in Cents',
						name: 'tax_amount_in_cents',
						type: 'number',
						default: 0,
					},
					{
						displayName: 'Transaction Fee Currency',
						name: 'transaction_fees_currency',
						type: 'string',
						default: '',
						placeholder: 'USD',
					},
					{
						displayName: 'Transaction Fee in Cents',
						name: 'transaction_fees_in_cents',
						type: 'number',
						default: 0,
					},
					{ displayName: 'Type', name: 'type', type: 'hidden', default: 'one_time' },
				],
			},
			{
				displayName: 'Subscription',
				name: 'subscription',
				values: [
					{ displayName: 'Amount in Cents', name: 'amount_in_cents', type: 'number', default: 0 },
					{ displayName: 'Cancelled At', name: 'canceled_at', type: 'dateTime', default: '' },
					{ displayName: 'Description', name: 'description', type: 'string', default: '' },
					{
						displayName: 'Discount Amount in Cents',
						name: 'discount_amount_in_cents',
						type: 'number',
						default: 0,
					},
					{ displayName: 'Discount Code', name: 'discount_code', type: 'string', default: '' },
					{
						displayName: 'Discount Description',
						name: 'discount_description',
						type: 'string',
						default: '',
					},
					{ displayName: 'Event Order', name: 'event_order', type: 'number', default: 0 },
					{ displayName: 'External ID', name: 'external_id', type: 'string', default: '' },
					{ displayName: 'Plan UUID', name: 'plan_uuid', type: 'string', default: '' },
					{ displayName: 'Prorated', name: 'prorated', type: 'boolean', default: false },
					{
						displayName: 'Proration Type',
						name: 'proration_type',
						type: 'options',
						options: [
							{ name: 'Differential', value: 'differential' },
							{ name: 'Differential MRR', value: 'differential_mrr' },
							{ name: 'Full', value: 'full' },
						],
						default: 'differential',
					},
					{ displayName: 'Quantity', name: 'quantity', type: 'number', default: 1 },
					{
						displayName: 'Service Period End',
						name: 'service_period_end',
						type: 'dateTime',
						default: '',
					},
					{
						displayName: 'Service Period Start',
						name: 'service_period_start',
						type: 'dateTime',
						default: '',
					},
					{
						displayName: 'Subscription External ID',
						name: 'subscription_external_id',
						type: 'string',
						default: '',
					},
					{
						displayName: 'Subscription Set External ID',
						name: 'subscription_set_external_id',
						type: 'string',
						default: '',
					},
					{
						displayName: 'Tax Amount in Cents',
						name: 'tax_amount_in_cents',
						type: 'number',
						default: 0,
					},
					{
						displayName: 'Transaction Fee Currency',
						name: 'transaction_fees_currency',
						type: 'string',
						default: '',
						placeholder: 'USD',
					},
					{
						displayName: 'Transaction Fee in Cents',
						name: 'transaction_fees_in_cents',
						type: 'number',
						default: 0,
					},
					{ displayName: 'Type', name: 'type', type: 'hidden', default: 'subscription' },
				],
			},
		],
	},
	{
		displayName: 'Transactions',
		name: 'transactions',
		type: 'fixedCollection',
		placeholder: 'Add Transaction',
		typeOptions: { multipleValues: true },
		default: {},
		displayOptions: { show: { resource: ['invoice'], operation: ['create'] } },
		options: [
			{
				displayName: 'Transaction',
				name: 'transaction',
				values: [
					{
						displayName: 'Amount in Cents',
						name: 'amount_in_cents',
						type: 'number',
						default: null,
						description:
							'The amount paid/refunded for this invoice. If this field is left empty it will default to full amount of the invoice. The sum of the partial payments/refunds should not exceed the invoiced amount.',
					},
					{
						displayName: 'Result',
						name: 'result',
						type: 'options',
						default: 'successful',
						options: [
							{ name: 'Successful', value: 'successful' },
							{ name: 'Failed', value: 'failed' },
						],
					},
					{
						displayName: 'Transaction Date',
						name: 'date',
						type: 'dateTime',
						default: '',
						description: 'The date when the transaction occurred',
					},
					{
						displayName: 'Transaction External ID',
						name: 'external_id',
						type: 'string',
						default: '',
						description: 'The external ID of the transaction',
					},
					{
						displayName: 'Type',
						name: 'type',
						type: 'options',
						default: 'payment',
						options: [
							{ name: 'Payment', value: 'payment' },
							{ name: 'Refund', value: 'refund' },
						],
					},
				],
			},
		],
	},
];
