import type { INodeProperties } from 'n8n-workflow';

export const createDescription: INodeProperties[] = [
	{
		displayName: 'Customer UUID',
		name: 'customerUUID',
		type: 'string',
		default: '',
		description: 'ChartMogul UUID of the Customer',
		displayOptions: { show: { resource: ['task'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { customer_uuid: '={{$value}}' } } },
	},
	{
		displayName: 'Task Details',
		name: 'task_details',
		type: 'string',
		default: '',
		description: 'A description of the task up to 255 characters',
		displayOptions: { show: { resource: ['task'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { task_details: '={{$value}}' } } },
	},
	{
		displayName: 'Assignee',
		name: 'assignee',
		type: 'string',
		default: '',
		placeholder: 'name@email.com',
		description: 'The email address of the ChartMogul user assigned to the task',
		displayOptions: { show: { resource: ['task'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { assignee: '={{$value}}' } } },
	},
	{
		displayName: 'Due Date',
		name: 'due_date',
		type: 'dateTime',
		default: '',
		description: 'The date when the task is due',
		displayOptions: { show: { resource: ['task'], operation: ['create'] } },
		required: true,
		routing: { request: { body: { due_date: '={{$value}}' } } },
	},
	{
		displayName: 'Completed',
		name: 'completed',
		type: 'boolean',
		default: false,
		description: 'Whether the task is completed or not',
		displayOptions: { show: { resource: ['task'], operation: ['create'] } },
	},
	{
		displayName: 'Completed At',
		name: 'completed_at',
		type: 'dateTime',
		default: '',
		description: 'The date when the task was completed',
		displayOptions: { show: { resource: ['task'], operation: ['create'], completed: [true] } },
		routing: { request: { body: { completed_at: '={{$value}}' } } },
	},
];
